[project]
name = "rag-time"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faiss-cpu>=1.13.2",
    "langchain>=1.2.15",
    "langchain-community>=0.4.1",
    "langchain-huggingface>=1.2.1",
    "langchain-openai>=1.1.12",
    "langchain-openrouter>=0.2.1",
    "langchain-text-splitters>=1.1.2",
    "torch>=2.9.0,<2.10.0",
    "pylate>=1.4.0",
    "rag_time",
    "qdrant-client>=1.17.1",
    "fastembed>=0.8.0",
]

[tool.uv]
package = true

[tool.uv.sources]
rag_time = { editable = true, path = "." }


[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "notebook>=7.5.5",
]


[tool.setuptools]
# On indique que le package 'rag_time' se trouve dans 'src'
package-dir = {"" = "src", "scripts" = "scripts"}

[tool.setuptools.packages.find]
# On demande à setuptools de chercher dans ces deux endroits
where = ["src", "."]
include = ["rag_time*", "scripts*"]

[project.scripts]
rag-embed = "scripts.embed_data:main"
rag-upload = "scripts.qdrant_upload:main"
rag-query = "scripts.retrieve:main"
