from __future__ import annotations

import dspy

from rag_time.dspy.objects.ticket_resolution import RelevanceJudgement


class RelevanceJudgeSignature(dspy.Signature):
    """Judge how relevant a set of retrieved documents is to a given query.

    You are an objective evaluation expert. Assess whether the retrieved documents
    actually address the query. Be strict: only give high scores when the documents
    clearly and directly answer or support the query.
    """

    query: str = dspy.InputField(desc="The user query or question being evaluated.")
    documents: str = dspy.InputField(
        desc="The retrieved documents or passages to evaluate for relevance."
    )
    judgement: RelevanceJudgement = dspy.OutputField(
        desc="Structured relevance judgement with a score and reasoning."
    )


class RelevanceJudge(dspy.Module):
    def __init__(self) -> None:
        super().__init__()
        self.predictor = dspy.asyncify(dspy.ChainOfThought(RelevanceJudgeSignature))

    async def forward(self, query: str, documents: list) -> RelevanceJudgement:
        docs_text = "\n\n".join(str(d) for d in documents) if documents else "(no documents retrieved)"
        result = await self.predictor(query=query, documents=docs_text)
        return result.judgement


class AnswerQualityJudgeSignature(dspy.Signature):
    """Evaluate the quality of a generated answer against a reference answer.

    You are an objective evaluation expert. Score the generated answer on three
    dimensions: answer quality vs the reference, relevance of the retrieved context,
    and how well the retrieved context was used in the answer.
    All scores must be floats between 0.0 and 1.0.
    """

    query: str = dspy.InputField(desc="The user query or question.")
    retrieved_documents: str = dspy.InputField(
        desc="The documents retrieved and used as context for the answer."
    )
    generated_answer: str = dspy.InputField(desc="The answer generated by the RAG pipeline.")
    reference_answer: str = dspy.InputField(
        desc="The ground-truth reference answer to compare against."
    )
    judgement: str = dspy.OutputField(
        desc=(
            "JSON object with keys: answer_quality (0-1), retrieval_relevance (0-1), "
            "retrieval_usage (0-1), reasoning (string). All float scores between 0.0 and 1.0."
        )
    )


__all__ = ["RelevanceJudge", "RelevanceJudgeSignature", "AnswerQualityJudgeSignature"]
